name: bookrec
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^5.2.1
  flutter_quill: ^11.4.1
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.8.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  palette_generator: ^0.3.3+7
  provider: ^6.1.5
  shimmer: ^3.0.0
  file_picker: ^10.2.0
  pdfx: ^2.9.2
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - .env
    
